apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  labels:
    name: converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
      - name: converter
        image: luxitkapoor/converter
        envFrom:
          - configMapRef:
              name: converter-configmap
          - secretRef:
              name: converter-secret
